Performing KNN on MNIST Dataset using custom written library

The input (sample) files can be downloaded from https://yann.lecun.com/exdb/mnist/

In [2]:
from mnist import MNIST
mndata = MNIST('samples')
train_images, train_labels = mndata.load_training()
test_images, test_labels = mndata.load_testing()

len(train_images), len(train_labels), len(test_images), len(test_labels)

(60000, 60000, 10000, 10000)

In [3]:
import numpy as np
import knn_definition
import random

In [4]:
train_images = np.array(train_images[:10000])
train_labels = np.array(train_labels[:10000])
test_images = np.array(test_images[:100])
test_labels = np.array(test_labels[:100])

KNN = knn_definition.KNN(10, train_images, test_images, train_labels, test_labels, 'Euclidean', 'Classification')

In [5]:
test_images.shape

(100, 784)

In [6]:
np.array(KNN.operation_stacked())

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 9, 0, 7, 4, 0, 1, 3, 1, 3, 4, 7, 2, 7, 1, 1, 1, 1, 7, 4, 1,
       3, 5, 1, 2, 4, 4, 6, 3, 5, 5, 6, 0, 4, 1, 9, 5, 7, 8, 9, 3, 7, 4,
       6, 4, 3, 0, 7, 0, 2, 9, 1, 7, 3, 7, 9, 7, 7, 6, 2, 7, 8, 4, 7, 3,
       6, 1, 3, 6, 4, 3, 1, 4, 1, 7, 6, 9], dtype=uint8)

In [7]:
KNN.accuracy()

95.0

Using KNN to perform regression and computing the MSE and MAE

In [8]:
x = np.linspace(0, 2 * np.pi, 10000)
x = x.reshape(-1, 1)
y = np.sin(x)

shuffled_combined = list(zip(x, y))
random.shuffle(shuffled_combined)
x_shuffled, y_shuffled = zip(*shuffled_combined)

x_shuffled = np.array(x_shuffled)
y_shuffled = np.array(y_shuffled)

X_train, X_test = x_shuffled[:8000], x_shuffled[8000:]
Y_train, Y_test = y_shuffled[:8000], y_shuffled[8000:]

In [9]:
KNN_reg = knn_definition.KNN(10, X_train, X_test, Y_train, Y_test, 'Manhattan', 'Regression')

In [10]:
np.array(KNN_reg.operation_stacked())

array([[ 0.0306601 ],
       [ 0.95284319],
       [-0.99072728],
       ...,
       [ 0.84538841],
       [ 0.68716071],
       [ 0.43279791]])

In [11]:
KNN_reg.mse()

array([1.14204533e-07])

In [12]:
KNN_reg.mae()

array([0.00021959])